version: '3.8'
services:
  # cms-backend:
  #   build: ./cms-backend
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
  #   depends_on:
  #     - db
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
